version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: telegrambot
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .  # Constrói a partir do Dockerfile na pasta atual
      dockerfile: Dockerfile
    container_name: python_api
    volumes:
      - .:/app
    working_dir: /app
    command: python bot_script.py
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/telegrambot
    depends_on:
      - db

volumes:
  mysql_data:
